// generated by scripts/gen-swap-icons.mjs - do not edit
import c_aleo from '../../assets/swap-icons/c-aleo.png';
import c_aptos from '../../assets/swap-icons/c-aptos.png';
import c_arb from '../../assets/swap-icons/c-arb.png';
import c_avax from '../../assets/swap-icons/c-avax.png';
import c_base from '../../assets/swap-icons/c-base.png';
import c_bch from '../../assets/swap-icons/c-bch.png';
import c_bera from '../../assets/swap-icons/c-bera.png';
import c_bsc from '../../assets/swap-icons/c-bsc.png';
import c_btc from '../../assets/swap-icons/c-btc.png';
import c_cardano from '../../assets/swap-icons/c-cardano.png';
import c_dash from '../../assets/swap-icons/c-dash.png';
import c_doge from '../../assets/swap-icons/c-doge.png';
import c_eth from '../../assets/swap-icons/c-eth.png';
import c_gaia from '../../assets/swap-icons/c-gaia.png';
import c_gnosis from '../../assets/swap-icons/c-gnosis.png';
import c_hypercore from '../../assets/swap-icons/c-hypercore.png';
import c_ltc from '../../assets/swap-icons/c-ltc.png';
import c_monad from '../../assets/swap-icons/c-monad.png';
import c_movement from '../../assets/swap-icons/c-movement.png';
import c_near from '../../assets/swap-icons/c-near.png';
import c_op from '../../assets/swap-icons/c-op.png';
import c_plasma from '../../assets/swap-icons/c-plasma.png';
import c_pol from '../../assets/swap-icons/c-pol.png';
import c_scroll from '../../assets/swap-icons/c-scroll.png';
import c_sol from '../../assets/swap-icons/c-sol.png';
import c_starknet from '../../assets/swap-icons/c-starknet.png';
import c_stellar from '../../assets/swap-icons/c-stellar.png';
import c_sui from '../../assets/swap-icons/c-sui.png';
import c_ton from '../../assets/swap-icons/c-ton.png';
import c_tron from '../../assets/swap-icons/c-tron.png';
import c_xlayer from '../../assets/swap-icons/c-xlayer.png';
import c_xrp from '../../assets/swap-icons/c-xrp.png';
import c_zec from '../../assets/swap-icons/c-zec.png';
import t_aave from '../../assets/swap-icons/t-aave.png';
import t_adi_token from '../../assets/swap-icons/t-adi-token.png';
import t_aleo from '../../assets/swap-icons/t-aleo.png';
import t_aptos from '../../assets/swap-icons/t-aptos.png';
import t_arbitrum from '../../assets/swap-icons/t-arbitrum.png';
import t_aster_2 from '../../assets/swap-icons/t-aster-2.png';
import t_aurora_near from '../../assets/swap-icons/t-aurora-near.png';
import t_avalanche_2 from '../../assets/swap-icons/t-avalanche-2.png';
import t_based_brett from '../../assets/swap-icons/t-based-brett.png';
import t_berachain_bera from '../../assets/swap-icons/t-berachain-bera.png';
import t_binancecoin from '../../assets/swap-icons/t-binancecoin.png';
import t_bitcoin from '../../assets/swap-icons/t-bitcoin.png';
import t_bitcoin_cash from '../../assets/swap-icons/t-bitcoin-cash.png';
import t_black_dragon from '../../assets/swap-icons/t-black-dragon.png';
import t_book_of_meme from '../../assets/swap-icons/t-book-of-meme.png';
import t_cardano from '../../assets/swap-icons/t-cardano.png';
import t_cash_cat from '../../assets/swap-icons/t-cash-cat.png';
import t_chainlink from '../../assets/swap-icons/t-chainlink.png';
import t_coca from '../../assets/swap-icons/t-coca.png';
import t_coinbase_wrapped_btc from '../../assets/swap-icons/t-coinbase-wrapped-btc.png';
import t_consumerfi_protocol from '../../assets/swap-icons/t-consumerfi-protocol.png';
import t_cosmos from '../../assets/swap-icons/t-cosmos.png';
import t_cow_protocol from '../../assets/swap-icons/t-cow-protocol.png';
import t_dai from '../../assets/swap-icons/t-dai.png';
import t_dash from '../../assets/swap-icons/t-dash.png';
import t_dogecoin from '../../assets/swap-icons/t-dogecoin.png';
import t_dogwifcoin from '../../assets/swap-icons/t-dogwifcoin.png';
import t_ethena_usde from '../../assets/swap-icons/t-ethena-usde.png';
import t_ethereum from '../../assets/swap-icons/t-ethereum.png';
import t_evaa_protocol from '../../assets/swap-icons/t-evaa-protocol.png';
import t_falcon_finance from '../../assets/swap-icons/t-falcon-finance.png';
import t_fogo from '../../assets/swap-icons/t-fogo.png';
import t_forgive_me_father from '../../assets/swap-icons/t-forgive-me-father.png';
import t_frax from '../../assets/swap-icons/t-frax.png';
import t_global_dollar from '../../assets/swap-icons/t-global-dollar.png';
import t_gmx from '../../assets/swap-icons/t-gmx.png';
import t_gnosis from '../../assets/swap-icons/t-gnosis.png';
import t_hapi from '../../assets/swap-icons/t-hapi.png';
import t_hemi_bitcoin from '../../assets/swap-icons/t-hemi-bitcoin.png';
import t_hyperliquid from '../../assets/swap-icons/t-hyperliquid.png';
import t_infinex_2 from '../../assets/swap-icons/t-infinex-2.png';
import t_jambo_2 from '../../assets/swap-icons/t-jambo-2.png';
import t_kaito from '../../assets/swap-icons/t-kaito.png';
import t_kyber_network_crystal from '../../assets/swap-icons/t-kyber-network-crystal.png';
import t_litecoin from '../../assets/swap-icons/t-litecoin.png';
import t_loud from '../../assets/swap-icons/t-loud.png';
import t_melania_meme from '../../assets/swap-icons/t-melania-meme.png';
import t_meta_pool from '../../assets/swap-icons/t-meta-pool.png';
import t_mog_coin from '../../assets/swap-icons/t-mog-coin.png';
import t_monad from '../../assets/swap-icons/t-monad.png';
import t_monerium_eur_money_2 from '../../assets/swap-icons/t-monerium-eur-money-2.png';
import t_monerium_gbp_emoney from '../../assets/swap-icons/t-monerium-gbp-emoney.png';
import t_movement from '../../assets/swap-icons/t-movement.png';
import t_near from '../../assets/swap-icons/t-near.png';
import t_nearkat from '../../assets/swap-icons/t-nearkat.png';
import t_nearkat_2 from '../../assets/swap-icons/t-nearkat-2.png';
import t_npro from '../../assets/swap-icons/t-npro.png';
import t_official_trump from '../../assets/swap-icons/t-official-trump.png';
import t_okb from '../../assets/swap-icons/t-okb.png';
import t_optimism from '../../assets/swap-icons/t-optimism.png';
import t_pepe from '../../assets/swap-icons/t-pepe.png';
import t_plasma from '../../assets/swap-icons/t-plasma.png';
import t_polygon_ecosystem_token from '../../assets/swap-icons/t-polygon-ecosystem-token.png';
import t_pons from '../../assets/swap-icons/t-pons.png';
import t_publicai from '../../assets/swap-icons/t-publicai.png';
import t_pudgy_penguins from '../../assets/swap-icons/t-pudgy-penguins.png';
import t_rhea_2 from '../../assets/swap-icons/t-rhea-2.png';
import t_ripple from '../../assets/swap-icons/t-ripple.png';
import t_safe from '../../assets/swap-icons/t-safe.png';
import t_scroll from '../../assets/swap-icons/t-scroll.png';
import t_shiba_inu from '../../assets/swap-icons/t-shiba-inu.png';
import t_shitzu from '../../assets/swap-icons/t-shitzu.png';
import t_solana from '../../assets/swap-icons/t-solana.png';
import t_spx6900 from '../../assets/swap-icons/t-spx6900.png';
import t_staked_near from '../../assets/swap-icons/t-staked-near.png';
import t_starknet from '../../assets/swap-icons/t-starknet.png';
import t_stellar from '../../assets/swap-icons/t-stellar.png';
import t_sui from '../../assets/swap-icons/t-sui.png';
import t_sweatcoin from '../../assets/swap-icons/t-sweatcoin.png';
import t_tether from '../../assets/swap-icons/t-tether.png';
import t_tether_gold from '../../assets/swap-icons/t-tether-gold.png';
import t_the_open_network from '../../assets/swap-icons/t-the-open-network.png';
import t_thor_wallet from '../../assets/swap-icons/t-thor-wallet.png';
import t_tron from '../../assets/swap-icons/t-tron.png';
import t_turbo from '../../assets/swap-icons/t-turbo.png';
import t_uniswap from '../../assets/swap-icons/t-uniswap.png';
import t_usd_coin from '../../assets/swap-icons/t-usd-coin.png';
import t_usd1_wlfi from '../../assets/swap-icons/t-usd1-wlfi.png';
import t_usdt0 from '../../assets/swap-icons/t-usdt0.png';
import t_venice_token from '../../assets/swap-icons/t-venice-token.png';
import t_wrapped_near from '../../assets/swap-icons/t-wrapped-near.png';
import t_xdai from '../../assets/swap-icons/t-xdai.png';

/** token logos by lowercase symbol (one per symbol, every chain shares it) */
export const TOKEN_ICONS: Partial<Record<string, string>> = {
  $wif: t_dogwifcoin,
  aave: t_aave,
  ada: t_cardano,
  adi: t_adi_token,
  aleo: t_aleo,
  apt: t_aptos,
  aptos: t_aptos,
  arb: t_arbitrum,
  aster: t_aster_2,
  aurora: t_aurora_near,
  avax: t_avalanche_2,
  bch: t_bitcoin_cash,
  bera: t_berachain_bera,
  blackdragon: t_black_dragon,
  bnb: t_binancecoin,
  bome: t_book_of_meme,
  brett: t_based_brett,
  bsc: t_binancecoin,
  btc: t_bitcoin,
  'btc(omni)': t_bitcoin,
  cardano: t_cardano,
  cashcat: t_cash_cat,
  cbbtc: t_coinbase_wrapped_btc,
  cfi: t_consumerfi_protocol,
  coca: t_coca,
  cow: t_cow_protocol,
  dai: t_dai,
  dash: t_dash,
  doge: t_dogecoin,
  eth: t_ethereum,
  eure: t_monerium_eur_money_2,
  evaa: t_evaa_protocol,
  fogo: t_fogo,
  frax: t_frax,
  gaia: t_cosmos,
  gbpe: t_monerium_gbp_emoney,
  gmx: t_gmx,
  gno: t_gnosis,
  gnosis: t_gnosis,
  gram: t_the_open_network,
  hapi: t_hapi,
  hemibtc: t_hemi_bitcoin,
  hypercore: t_hyperliquid,
  inx: t_infinex_2,
  jambo: t_jambo_2,
  kaito: t_kaito,
  knc: t_kyber_network_crystal,
  link: t_chainlink,
  loud: t_loud,
  ltc: t_litecoin,
  melania: t_melania_meme,
  mog: t_mog_coin,
  mon: t_monad,
  monad: t_monad,
  move: t_movement,
  movement: t_movement,
  mpdao: t_meta_pool,
  near: t_near,
  nearkat: t_nearkat,
  npro: t_npro,
  nrusdt: t_tether,
  okb: t_okb,
  op: t_optimism,
  pengu: t_pudgy_penguins,
  pepe: t_pepe,
  plasma: t_plasma,
  pol: t_polygon_ecosystem_token,
  pons: t_pons,
  public: t_publicai,
  purge: t_forgive_me_father,
  rhea: t_rhea_2,
  safe: t_safe,
  scroll: t_scroll,
  shib: t_shiba_inu,
  shitzu: t_shitzu,
  sol: t_solana,
  spx: t_spx6900,
  starknet: t_starknet,
  stellar: t_stellar,
  stnear: t_staked_near,
  strk: t_starknet,
  sui: t_sui,
  susdc: t_usd_coin,
  sweat: t_sweatcoin,
  titn: t_thor_wallet,
  ton: t_the_open_network,
  tron: t_tron,
  trump: t_official_trump,
  trx: t_tron,
  turbo: t_turbo,
  uni: t_uniswap,
  usad: t_usd_coin,
  usd1: t_usd1_wlfi,
  usdc: t_usd_coin,
  usdcx: t_usd_coin,
  usde: t_ethena_usde,
  usdf: t_falcon_finance,
  usdg: t_global_dollar,
  usdt: t_tether,
  usdt0: t_usdt0,
  'usdt0(deprecated)': t_usdt0,
  vvv: t_venice_token,
  wbtc: t_bitcoin,
  weth: t_ethereum,
  wnear: t_wrapped_near,
  wnearkat: t_nearkat_2,
  xaut: t_tether_gold,
  xbtc: t_bitcoin,
  xdai: t_xdai,
  xlayer: t_okb,
  xlm: t_stellar,
  xpl: t_plasma,
  'xpl_(deprecated)': t_plasma,
  xrp: t_ripple,
};

/** chain logos by near's chain code */
export const CHAIN_ICONS: Partial<Record<string, string>> = {
  aleo: c_aleo,
  aptos: c_aptos,
  arb: c_arb,
  avax: c_avax,
  base: c_base,
  bch: c_bch,
  bera: c_bera,
  bsc: c_bsc,
  btc: c_btc,
  cardano: c_cardano,
  dash: c_dash,
  doge: c_doge,
  eth: c_eth,
  gaia: c_gaia,
  gnosis: c_gnosis,
  hypercore: c_hypercore,
  ltc: c_ltc,
  monad: c_monad,
  movement: c_movement,
  near: c_near,
  op: c_op,
  plasma: c_plasma,
  pol: c_pol,
  scroll: c_scroll,
  sol: c_sol,
  starknet: c_starknet,
  stellar: c_stellar,
  sui: c_sui,
  ton: c_ton,
  tron: c_tron,
  xlayer: c_xlayer,
  xrp: c_xrp,
  zec: c_zec,
};
