// generated by scripts/gen-registry-icons.mjs from @penumbrafi/registry - do not edit
import { setBundledIconResolver } from '@repo/ui/components/ui/asset-icon/bundled-icons';
import i00e7309216 from '../../assets/registry-icons/00e7309216.svg';
import i01035c132f from '../../assets/registry-icons/01035c132f.png';
import i021f225fc5 from '../../assets/registry-icons/021f225fc5.png';
import i030f5b0e47 from '../../assets/registry-icons/030f5b0e47.svg';
import i03667423f6 from '../../assets/registry-icons/03667423f6.svg';
import i04d1004375 from '../../assets/registry-icons/04d1004375.png';
import i055b238dbc from '../../assets/registry-icons/055b238dbc.png';
import i094aef24b8 from '../../assets/registry-icons/094aef24b8.png';
import i09d3558d61 from '../../assets/registry-icons/09d3558d61.png';
import i0b2388457d from '../../assets/registry-icons/0b2388457d.png';
import i0b65a8836f from '../../assets/registry-icons/0b65a8836f.png';
import i0e091992b8 from '../../assets/registry-icons/0e091992b8.png';
import i0eaba6fb93 from '../../assets/registry-icons/0eaba6fb93.png';
import i0f23654af5 from '../../assets/registry-icons/0f23654af5.svg';
import i10b805e232 from '../../assets/registry-icons/10b805e232.png';
import i1109c55323 from '../../assets/registry-icons/1109c55323.svg';
import i12c54c243c from '../../assets/registry-icons/12c54c243c.svg';
import i1508b32c6d from '../../assets/registry-icons/1508b32c6d.svg';
import i15ef186680 from '../../assets/registry-icons/15ef186680.svg';
import i173c7ff18d from '../../assets/registry-icons/173c7ff18d.png';
import i17fb8d83eb from '../../assets/registry-icons/17fb8d83eb.svg';
import i182a31712b from '../../assets/registry-icons/182a31712b.png';
import i18ded46569 from '../../assets/registry-icons/18ded46569.png';
import i1923bd6069 from '../../assets/registry-icons/1923bd6069.png';
import i1a2f86a165 from '../../assets/registry-icons/1a2f86a165.png';
import i1b294209cc from '../../assets/registry-icons/1b294209cc.png';
import i1baa8fe565 from '../../assets/registry-icons/1baa8fe565.png';
import i1be53c44a4 from '../../assets/registry-icons/1be53c44a4.svg';
import i210971545d from '../../assets/registry-icons/210971545d.svg';
import i216c6efea4 from '../../assets/registry-icons/216c6efea4.svg';
import i2465aa073c from '../../assets/registry-icons/2465aa073c.png';
import i254d6b3e49 from '../../assets/registry-icons/254d6b3e49.png';
import i259850e3f4 from '../../assets/registry-icons/259850e3f4.png';
import i26915a1426 from '../../assets/registry-icons/26915a1426.png';
import i27d6bd057f from '../../assets/registry-icons/27d6bd057f.svg';
import i2a03e698ce from '../../assets/registry-icons/2a03e698ce.png';
import i2b00b8ddab from '../../assets/registry-icons/2b00b8ddab.png';
import i2f0a3ef718 from '../../assets/registry-icons/2f0a3ef718.png';
import i306596012a from '../../assets/registry-icons/306596012a.png';
import i310dd877df from '../../assets/registry-icons/310dd877df.png';
import i31fa83f2c2 from '../../assets/registry-icons/31fa83f2c2.png';
import i333ea8b1d8 from '../../assets/registry-icons/333ea8b1d8.svg';
import i3368ee443d from '../../assets/registry-icons/3368ee443d.svg';
import i34b8468c3b from '../../assets/registry-icons/34b8468c3b.png';
import i3581aca4aa from '../../assets/registry-icons/3581aca4aa.png';
import i35b6e74b8e from '../../assets/registry-icons/35b6e74b8e.svg';
import i372d6a99b0 from '../../assets/registry-icons/372d6a99b0.png';
import i38386c7164 from '../../assets/registry-icons/38386c7164.svg';
import i389ec387da from '../../assets/registry-icons/389ec387da.png';
import i397847b876 from '../../assets/registry-icons/397847b876.svg';
import i39798ab9cb from '../../assets/registry-icons/39798ab9cb.png';
import i3a0c96d473 from '../../assets/registry-icons/3a0c96d473.png';
import i3a7002721a from '../../assets/registry-icons/3a7002721a.png';
import i3bc9dcbde5 from '../../assets/registry-icons/3bc9dcbde5.svg';
import i3f00fb7ec3 from '../../assets/registry-icons/3f00fb7ec3.png';
import i3ff85848ca from '../../assets/registry-icons/3ff85848ca.png';
import i40c2da483c from '../../assets/registry-icons/40c2da483c.png';
import i41d943dd96 from '../../assets/registry-icons/41d943dd96.png';
import i441417b857 from '../../assets/registry-icons/441417b857.png';
import i468f93f10c from '../../assets/registry-icons/468f93f10c.png';
import i47256f25ce from '../../assets/registry-icons/47256f25ce.png';
import i48dfe1b067 from '../../assets/registry-icons/48dfe1b067.png';
import i493bdd7339 from '../../assets/registry-icons/493bdd7339.png';
import i4a2f48e34b from '../../assets/registry-icons/4a2f48e34b.png';
import i4d07206805 from '../../assets/registry-icons/4d07206805.png';
import i4ee7b0fc7a from '../../assets/registry-icons/4ee7b0fc7a.png';
import i4f1d5c10b7 from '../../assets/registry-icons/4f1d5c10b7.png';
import i52d3c2bb10 from '../../assets/registry-icons/52d3c2bb10.png';
import i559401a29e from '../../assets/registry-icons/559401a29e.png';
import i580b8f217c from '../../assets/registry-icons/580b8f217c.png';
import i596f810aeb from '../../assets/registry-icons/596f810aeb.svg';
import i59784c612b from '../../assets/registry-icons/59784c612b.png';
import i5beeac4b96 from '../../assets/registry-icons/5beeac4b96.png';
import i5db90b3274 from '../../assets/registry-icons/5db90b3274.png';
import i5e4a64289a from '../../assets/registry-icons/5e4a64289a.png';
import i5e61ef415e from '../../assets/registry-icons/5e61ef415e.png';
import i615cb5e86e from '../../assets/registry-icons/615cb5e86e.svg';
import i63a61e5db4 from '../../assets/registry-icons/63a61e5db4.png';
import i651fd1c3fd from '../../assets/registry-icons/651fd1c3fd.png';
import i66441b161c from '../../assets/registry-icons/66441b161c.svg';
import i66c14b9469 from '../../assets/registry-icons/66c14b9469.svg';
import i68f65fd331 from '../../assets/registry-icons/68f65fd331.svg';
import i6ae4668bb3 from '../../assets/registry-icons/6ae4668bb3.svg';
import i6d0420ff93 from '../../assets/registry-icons/6d0420ff93.png';
import i71479bc69c from '../../assets/registry-icons/71479bc69c.svg';
import i7177b164b2 from '../../assets/registry-icons/7177b164b2.svg';
import i72d41db298 from '../../assets/registry-icons/72d41db298.svg';
import i76a215ca49 from '../../assets/registry-icons/76a215ca49.svg';
import i76b58bf33f from '../../assets/registry-icons/76b58bf33f.png';
import i772f5ae348 from '../../assets/registry-icons/772f5ae348.svg';
import i78922d6dbb from '../../assets/registry-icons/78922d6dbb.svg';
import i78b9d58160 from '../../assets/registry-icons/78b9d58160.png';
import i79db448708 from '../../assets/registry-icons/79db448708.svg';
import i7f2cd6b7d7 from '../../assets/registry-icons/7f2cd6b7d7.png';
import i7f4b545432 from '../../assets/registry-icons/7f4b545432.png';
import i7f6edc5f10 from '../../assets/registry-icons/7f6edc5f10.png';
import i825f611496 from '../../assets/registry-icons/825f611496.png';
import i853a575510 from '../../assets/registry-icons/853a575510.png';
import i853b0190e7 from '../../assets/registry-icons/853b0190e7.png';
import i8989afdca1 from '../../assets/registry-icons/8989afdca1.png';
import i89a2b79afa from '../../assets/registry-icons/89a2b79afa.png';
import i8bc1674803 from '../../assets/registry-icons/8bc1674803.png';
import i8d0d029104 from '../../assets/registry-icons/8d0d029104.png';
import i90d13fdbeb from '../../assets/registry-icons/90d13fdbeb.png';
import i90d9d74757 from '../../assets/registry-icons/90d9d74757.png';
import i952480dd23 from '../../assets/registry-icons/952480dd23.png';
import i96a43f3561 from '../../assets/registry-icons/96a43f3561.png';
import i97a5ee4b50 from '../../assets/registry-icons/97a5ee4b50.png';
import i98239ebcd8 from '../../assets/registry-icons/98239ebcd8.png';
import i9836891aec from '../../assets/registry-icons/9836891aec.png';
import i99b7c8b38c from '../../assets/registry-icons/99b7c8b38c.svg';
import i99f0ded1df from '../../assets/registry-icons/99f0ded1df.png';
import i9a350ee8f7 from '../../assets/registry-icons/9a350ee8f7.png';
import i9a389a97d8 from '../../assets/registry-icons/9a389a97d8.png';
import i9b3a79e101 from '../../assets/registry-icons/9b3a79e101.png';
import i9cd6c3507d from '../../assets/registry-icons/9cd6c3507d.png';
import i9f5f5c1a1c from '../../assets/registry-icons/9f5f5c1a1c.png';
import ia02b4e4ca4 from '../../assets/registry-icons/a02b4e4ca4.png';
import ia06fdbda1d from '../../assets/registry-icons/a06fdbda1d.svg';
import ia2206a48af from '../../assets/registry-icons/a2206a48af.svg';
import ia26b545c11 from '../../assets/registry-icons/a26b545c11.png';
import ia2be258f84 from '../../assets/registry-icons/a2be258f84.png';
import ia4e123cb6a from '../../assets/registry-icons/a4e123cb6a.png';
import ia5625149a8 from '../../assets/registry-icons/a5625149a8.png';
import ia5bfd7cf2c from '../../assets/registry-icons/a5bfd7cf2c.svg';
import ia6d5c18819 from '../../assets/registry-icons/a6d5c18819.png';
import iaa6154de29 from '../../assets/registry-icons/aa6154de29.png';
import iadb69a712b from '../../assets/registry-icons/adb69a712b.svg';
import iae9b30eeb7 from '../../assets/registry-icons/ae9b30eeb7.png';
import iaef385d716 from '../../assets/registry-icons/aef385d716.png';
import iaf2488d2ef from '../../assets/registry-icons/af2488d2ef.png';
import ib23070d776 from '../../assets/registry-icons/b23070d776.png';
import ib3e097fd53 from '../../assets/registry-icons/b3e097fd53.png';
import ib4cdd48718 from '../../assets/registry-icons/b4cdd48718.png';
import ib68f66b0bd from '../../assets/registry-icons/b68f66b0bd.png';
import ib71c7307df from '../../assets/registry-icons/b71c7307df.svg';
import ib75238b883 from '../../assets/registry-icons/b75238b883.png';
import ib9daafa508 from '../../assets/registry-icons/b9daafa508.png';
import ibd201b6ebb from '../../assets/registry-icons/bd201b6ebb.png';
import ibe07b30e31 from '../../assets/registry-icons/be07b30e31.png';
import ibef990e9d2 from '../../assets/registry-icons/bef990e9d2.png';
import ic0234644b7 from '../../assets/registry-icons/c0234644b7.png';
import ic12b3a66dd from '../../assets/registry-icons/c12b3a66dd.png';
import ic1eae3bc4f from '../../assets/registry-icons/c1eae3bc4f.svg';
import ic35402c892 from '../../assets/registry-icons/c35402c892.svg';
import ic46726e45e from '../../assets/registry-icons/c46726e45e.svg';
import ic4f4df77dc from '../../assets/registry-icons/c4f4df77dc.png';
import ic6ae2a6eed from '../../assets/registry-icons/c6ae2a6eed.png';
import ic6c2c8bb5e from '../../assets/registry-icons/c6c2c8bb5e.svg';
import icb61bc6307 from '../../assets/registry-icons/cb61bc6307.png';
import icbb7bcbf4c from '../../assets/registry-icons/cbb7bcbf4c.png';
import icbbed31233 from '../../assets/registry-icons/cbbed31233.png';
import id242921d7f from '../../assets/registry-icons/d242921d7f.svg';
import id35e262080 from '../../assets/registry-icons/d35e262080.png';
import id6bd3c857c from '../../assets/registry-icons/d6bd3c857c.svg';
import id9defa02a3 from '../../assets/registry-icons/d9defa02a3.png';
import idec2a2b971 from '../../assets/registry-icons/dec2a2b971.svg';
import idf5a29e946 from '../../assets/registry-icons/df5a29e946.png';
import ie0802804ab from '../../assets/registry-icons/e0802804ab.png';
import ie119d2e96f from '../../assets/registry-icons/e119d2e96f.png';
import ie40544b181 from '../../assets/registry-icons/e40544b181.svg';
import ie67de2c670 from '../../assets/registry-icons/e67de2c670.png';
import ie824f70081 from '../../assets/registry-icons/e824f70081.png';
import ie843ca19cf from '../../assets/registry-icons/e843ca19cf.png';
import ieb28dd591c from '../../assets/registry-icons/eb28dd591c.png';
import iec9c100c89 from '../../assets/registry-icons/ec9c100c89.png';
import ied89d0dfec from '../../assets/registry-icons/ed89d0dfec.png';
import iede2e30222 from '../../assets/registry-icons/ede2e30222.png';
import iee5d7d8ad0 from '../../assets/registry-icons/ee5d7d8ad0.svg';
import if06927e235 from '../../assets/registry-icons/f06927e235.svg';
import if34c63bf0a from '../../assets/registry-icons/f34c63bf0a.png';
import if3518d2c3d from '../../assets/registry-icons/f3518d2c3d.png';
import if3d610bea8 from '../../assets/registry-icons/f3d610bea8.png';
import if728596cce from '../../assets/registry-icons/f728596cce.png';
import if7e98cc438 from '../../assets/registry-icons/f7e98cc438.png';
import ifa2d1608dd from '../../assets/registry-icons/fa2d1608dd.png';
import ifa90b737ca from '../../assets/registry-icons/fa90b737ca.svg';
import ifb4962443e from '../../assets/registry-icons/fb4962443e.png';
import ifc3aaa441c from '../../assets/registry-icons/fc3aaa441c.png';
import ifefe569bb4 from '../../assets/registry-icons/fefe569bb4.png';
import iffa1bb4e17 from '../../assets/registry-icons/ffa1bb4e17.png';

const BY_URL: Record<string, string> = {
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/0l/images/libra.png':
    i0f23654af5,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/0l/images/libra.svg':
    i0f23654af5,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/aptos/images/apt-dm.svg':
    ib71c7307df,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/aptos/images/aptos.svg':
    iee5d7d8ad0,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/arbitrum/images/arb.png':
    id6bd3c857c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/arbitrum/images/arb.svg':
    id6bd3c857c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/avail/images/avail.png':
    ie119d2e96f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/avail/images/avail.svg':
    ie119d2e96f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/binancesmartchain/images/bnb.png':
    if06927e235,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/binancesmartchain/images/bnb.svg':
    if06927e235,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/bitcoin/images/btc.png':
    i35b6e74b8e,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/bitcoin/images/btc.svg':
    i35b6e74b8e,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/bitcoincash/images/bch.png':
    i596f810aeb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/bitcoincash/images/bch.svg':
    i596f810aeb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/dogecoin/images/doge.png':
    icbbed31233,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/dogecoin/images/doge.svg':
    icbbed31233,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/beast.png':
    i825f611496,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/eth-white.png':
    i3368ee443d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/eth-white.svg':
    i3368ee443d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/eure.png':
    ifa90b737ca,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/eure.svg':
    ifa90b737ca,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/glto.png':
    i1b294209cc,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/glto.svg':
    i1b294209cc,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/link.png':
    i1be53c44a4,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/link.svg':
    i1be53c44a4,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/pepe.png':
    i39798ab9cb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/pepe.svg':
    i39798ab9cb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/shib.svg':
    ia6d5c18819,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/uni.svg':
    i306596012a,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/usdc.png':
    i397847b876,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/usdc.svg':
    i397847b876,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/usdt.png':
    i1109c55323,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/usdt.svg':
    i1109c55323,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/usdt_logomark.png':
    ic0234644b7,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/wbtc.png':
    ib68f66b0bd,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/wbtc.svg':
    ib68f66b0bd,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/filecoin/images/fil.png':
    i68f65fd331,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/filecoin/images/fil.svg':
    i68f65fd331,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/internetcomputer/images/ckbtc.png':
    i216c6efea4,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/internetcomputer/images/ckbtc.svg':
    i216c6efea4,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/internetcomputer/images/icp.png':
    ic1eae3bc4f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/internetcomputer/images/icp.svg':
    ic1eae3bc4f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/litecoin/images/ltc.png':
    ia5bfd7cf2c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/litecoin/images/ltc.svg':
    ia5bfd7cf2c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/movement/images/move.png':
    i094aef24b8,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/movement/images/move.svg':
    i094aef24b8,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/optimism/images/op.png':
    ic35402c892,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/optimism/images/op.svg':
    ic35402c892,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/polkadot/images/dot.png':
    i7177b164b2,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/polkadot/images/dot.svg':
    i7177b164b2,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/polygon/images/matic-purple.png':
    ia2206a48af,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/polygon/images/matic-purple.svg':
    ia2206a48af,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/rootstock/images/rbtc.png':
    i66441b161c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/rootstock/images/rbtc.svg':
    i66441b161c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/solana/images/pengu.png':
    i441417b857,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/solana/images/sol.svg':
    i79db448708,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/solana/images/sol_circle.png':
    i772f5ae348,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/solana/images/sol_circle.svg':
    i772f5ae348,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/solana/images/trump.png':
    id9defa02a3,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/sui/images/sui.svg':
    i15ef186680,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ton/images/ton.png':
    i03667423f6,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ton/images/ton.svg':
    i03667423f6,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/tron/images/trx.png':
    ic46726e45e,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/tron/images/trx.svg':
    ic46726e45e,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/xrpl/images/xrp.png':
    i17fb8d83eb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/xrpl/images/xrp.svg':
    i17fb8d83eb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/zcash/images/zec.png':
    ia2be258f84,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/aioz/images/aioz.png':
    i00e7309216,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/aioz/images/aioz.svg':
    i00e7309216,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/babylon/images/eBABY.svg':
    i3bc9dcbde5,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/celestia/images/celestia.png':
    idf5a29e946,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/celestia/images/celestia.svg':
    idf5a29e946,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/art.png':
    iae9b30eeb7,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.png':
    i333ea8b1d8,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg':
    i333ea8b1d8,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/nthr.png':
    i99f0ded1df,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/phmn.png':
    i580b8f217c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/resp.png':
    i493bdd7339,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/stars.png':
    i27d6bd057f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/stars.svg':
    i27d6bd057f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/dydx/images/dydx-circle.svg':
    i6ae4668bb3,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/dydx/images/dydx.png':
    i210971545d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/dydx/images/dydx.svg':
    i210971545d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/dymension/images/dymension-logo.png':
    i66c14b9469,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/dymension/images/dymension-logo.svg':
    i66c14b9469,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/epix/images/epix.png':
    iadb69a712b,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/epix/images/epix.svg':
    iadb69a712b,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/fetchhub/images/fet.png':
    ia06fdbda1d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/fetchhub/images/fet.svg':
    ia06fdbda1d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/fetchhub/images/fet_white.png':
    i99b7c8b38c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/fetchhub/images/fet_white.svg':
    i99b7c8b38c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/NBZ.png':
    i18ded46569,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/NBZ.svg':
    i18ded46569,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/ampinj.png':
    i651fd1c3fd,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/ausd.png':
    ie67de2c670,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/autism.png':
    i96a43f3561,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/binj.png':
    ib3e097fd53,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/bitcoin.png':
    iaef385d716,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/brics.png':
    i055b238dbc,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/cosmo.png':
    ibef990e9d2,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/crypto.png':
    id35e262080,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/cw20drugs.png':
    i5beeac4b96,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/drugs.png':
    ie824f70081,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/hava.png':
    i9cd6c3507d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/helixpoint.png':
    i76b58bf33f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/hinj.png':
    ia4e123cb6a,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/inc.png':
    if3d610bea8,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/inj.png':
    i76a215ca49,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/inj.svg':
    i76a215ca49,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/judo.png':
    ieb28dd591c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/motion.png':
    i52d3c2bb10,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/natom.png':
    if7e98cc438,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/nept.png':
    i468f93f10c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/ninj.png':
    ifefe569bb4,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/ninja.png':
    i0b2388457d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/ninpo.png':
    i9b3a79e101,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/nsol.png':
    i3a7002721a,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/ntia.png':
    i254d6b3e49,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/nusdc.png':
    i89a2b79afa,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/nusdt.png':
    i31fa83f2c2,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/nweth.png':
    i5e4a64289a,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/oyci.png':
    i2b00b8ddab,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/syn.ash.png':
    ia5625149a8,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/syn.png':
    i1baa8fe565,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/talis.png':
    ib75238b883,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/wgmi.png':
    icbb7bcbf4c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/xtalis.png':
    if3518d2c3d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/hard.png':
    ie40544b181,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/hard.svg':
    ie40544b181,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/kava.png':
    i71479bc69c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/kava.svg':
    i71479bc69c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/swp.png': i030f5b0e47,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/swp.svg': i030f5b0e47,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/usdx.png':
    i1508b32c6d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/usdx.svg':
    i1508b32c6d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/USDN.png':
    i8d0d029104,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/USDN.svg':
    i8d0d029104,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/frnz.png':
    i182a31712b,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/stake.png':
    i72d41db298,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/stake.svg':
    i72d41db298,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/usdy.png':
    i38386c7164,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/usdy.svg':
    i38386c7164,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/BA-BA.png':
    i9a350ee8f7,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/BAG.png':
    i90d9d74757,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/BRNZ.png':
    i952480dd23,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/BVT0.png':
    i173c7ff18d,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/BVT1.png':
    i9f5f5c1a1c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/BWH.png':
    i3581aca4aa,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/CAC.png':
    i97a5ee4b50,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/CDT.svg':
    i2f0a3ef718,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/COCA.png':
    ied89d0dfec,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/COOK.png':
    ie0802804ab,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/CosmoUSD.png':
    i372d6a99b0,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/CrazyHorse.png':
    if34c63bf0a,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/FOST.png':
    ib9daafa508,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/LAB.png':
    i259850e3f4,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/LABS.png':
    i26915a1426,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/MBRN.svg':
    ia26b545c11,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/MTC.png':
    i0eaba6fb93,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/NINEDOLLERS.png':
    ic4f4df77dc,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/PBB.png':
    i0b65a8836f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/RAPTR.png':
    ic12b3a66dd,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/SLAYER.png':
    i7f6edc5f10,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/STLTH.png':
    i47256f25ce,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/T7S.png':
    i0e091992b8,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/TURD.png':
    ibe07b30e31,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/WIHA.png':
    ib23070d776,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/XTRUMP.png':
    i021f225fc5,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/allin.png':
    i3a0c96d473,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/amposmo.png':
    i4f1d5c10b7,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ashLAB.png':
    i1a2f86a165,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ashion.png':
    i63a61e5db4,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/bOSMO.png':
    i90d13fdbeb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/badkid.png':
    iec9c100c89,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/bernese.png':
    i3f00fb7ec3,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/bomu.png':
    ifc3aaa441c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ckDOGE.png':
    i4ee7b0fc7a,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ckDOGE.svg':
    i4ee7b0fc7a,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/cult.png':
    icb61bc6307,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fATLAS.png':
    i5e61ef415e,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fBAD.png':
    ic6ae2a6eed,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fBULLS.png':
    i10b805e232,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fCEWT.png':
    i8989afdca1,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fCRYPTONIUM.png':
    i389ec387da,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fGECK.png':
    i310dd877df,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fHAM.png':
    i3ff85848ca,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fMAD.png':
    i34b8468c3b,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fNUT.png':
    i5db90b3274,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fSLOTH.png':
    if728596cce,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fWITCH.png':
    i2a03e698ce,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/fWIZ.png':
    ifa2d1608dd,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/gsi.png':
    i59784c612b,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ibc.png':
    ibd201b6ebb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ibcx.svg':
    idec2a2b971,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ion.png':
    iaa6154de29,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ion.svg':
    iaa6154de29,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/leg.png':
    i01035c132f,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/levana.png':
    i853b0190e7,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/levana.svg':
    i853b0190e7,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/milktia.png':
    i4d07206805,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/milktia.svg':
    i4d07206805,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/osmo.png':
    i78b9d58160,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/osmo.svg':
    i78b9d58160,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/quark.png':
    ie843ca19cf,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/sail.png':
    ia02b4e4ca4,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/sherpa.png':
    ib4cdd48718,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/shitmos.png':
    i1923bd6069,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/shitmos.svg':
    i1923bd6069,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/spice.png':
    i2465aa073c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/sqatom.svg':
    i78922d6dbb,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/sqbtc.svg':
    i615cb5e86e,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/sqosmo.svg':
    i9836891aec,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/sqtia.svg':
    i9a389a97d8,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/stibcx.png':
    ic6c2c8bb5e,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/stibcx.svg':
    ic6c2c8bb5e,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/stlth-circle.png':
    i8bc1674803,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/toro.png':
    i04d1004375,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/toro.svg':
    i04d1004375,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/usd.svg':
    i12c54c243c,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/wosmo.png':
    iaf2488d2ef,
  'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/ymos.png':
    i853a575510,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/ghostinnet.png': i98239ebcd8,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/penumbra-favicon.png':
    i41d943dd96,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/um.svg': id242921d7f,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid10n2srs5257a6nxq9x3fhcsqyc0wh8q2lp7f80qd7wlmzdm6znypse23mmh.png':
    i559401a29e,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid19jqf35xytm4ht9f8awtad9wxmfky0tjygug8390cewyqjwmyucqqkkrc9r.png':
    i48dfe1b067,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid19qcxdmkpry2zda9htt2wprpk32yc9nwjgmc0xvqwm8qz5afk6upsmg55hh.png':
    i6d0420ff93,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid1ar6hyxmvy0em86nclqgxc4qlauj9ct747g4dsx8tn6wthg9nuvrq099640.png':
    i7f2cd6b7d7,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid1gq4j0hh6grl6d7apwg8z5qj97q7uhkeq0tp9qr66xe03cyrjkyrskp7s6v.png':
    iede2e30222,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid1he9sez9r2yzc8dekh5w7vqqz6r5c557s8jjchmu3879e9lzn4g9q57k04c.png':
    i09d3558d61,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid1jf8tmgqaar2xdrhspmmuwyd6jt6hedjh0gz32pz4vwrmh93tvsyswth2sf.png':
    i7f4b545432,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid1ktcv24rwkp69mc6hf5g7kwpwrevy6mrzdsg07nq3za6z4fp72cyqf4aw3d.png':
    ifb4962443e,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid1mr4j6nh3za3wjptjr2uj2ssr3fg0gxxqgqg9vgjl7luqa3qur5zs3fj5w6.png':
    iffa1bb4e17,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/validators/penumbravalid1q2eu6p33ne58aq0xh2ramsftmxqtqzlzwpa6uy8tgygje39mzypsq6nuyw.png':
    i40c2da483c,
  'https://raw.githubusercontent.com/penumbrafi/registry/main/images/zec-hub.png': i4a2f48e34b,
};

/** the registry icons this build ships; any other url falls back to a monogram */
export const installRegistryIcons = (): void => {
  setBundledIconResolver((url: string) => BY_URL[url]);
};
