/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_walletkeys_free: (a: number, b: number) => void;
export const __wbg_watchonlywallet_free: (a: number, b: number) => void;
export const build_unsigned_transaction: (a: any, b: number, c: number, d: bigint, e: bigint, f: number, g: number, h: any, i: number, j: number) => [number, number, number];
export const complete_transaction: (a: number, b: number, c: any) => [number, number, number, number];
export const create_sign_request: (a: number, b: number, c: number, d: any, e: number, f: number) => [number, number, number, number];
export const generate_seed_phrase: () => [number, number, number, number];
export const get_commitment_proof_request: (a: number, b: number) => [number, number, number, number];
export const num_threads: () => number;
export const parse_signature_response: (a: number, b: number) => [number, number, number];
export const validate_seed_phrase: (a: number, b: number) => number;
export const version: () => [number, number];
export const walletkeys_calculate_balance: (a: number, b: any, c: any) => [bigint, number, number];
export const walletkeys_decrypt_transaction_memos: (a: number, b: number, c: number) => [number, number, number];
export const walletkeys_export_fvk_qr_hex: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const walletkeys_from_seed_phrase: (a: number, b: number) => [number, number, number];
export const walletkeys_get_address: (a: number) => [number, number];
export const walletkeys_get_fvk_hex: (a: number) => [number, number];
export const walletkeys_get_receiving_address: (a: number, b: number) => [number, number];
export const walletkeys_get_receiving_address_at: (a: number, b: number, c: number) => [number, number];
export const walletkeys_scan_actions: (a: number, b: any) => [number, number, number];
export const walletkeys_scan_actions_parallel: (a: number, b: number, c: number) => [number, number, number];
export const watchonlywallet_decrypt_transaction_memos: (a: number, b: number, c: number) => [number, number, number];
export const watchonlywallet_export_fvk_hex: (a: number) => [number, number];
export const watchonlywallet_from_fvk_bytes: (a: number, b: number, c: number, d: number) => [number, number, number];
export const watchonlywallet_from_qr_hex: (a: number, b: number) => [number, number, number];
export const watchonlywallet_get_account_index: (a: number) => number;
export const watchonlywallet_get_address: (a: number) => [number, number];
export const watchonlywallet_get_address_at: (a: number, b: number) => [number, number];
export const watchonlywallet_is_mainnet: (a: number) => number;
export const watchonlywallet_scan_actions_parallel: (a: number, b: number, c: number) => [number, number, number];
export const init: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
