/* tslint:disable */
/* eslint-disable */
export const build_delegation_pczt: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number) => [number, number, number, number];
export const build_vote_commitment_wire: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number, number];
export const build_vote_shares_from_recovery: (a: number, b: number, c: bigint, d: bigint) => [number, number, number, number];
export const cast_vote_hot_wire: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number, number];
export const finalize_delegation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
export const generate_voting_hotkey: (a: number, b: number) => [number, number, number, number];
export const pir_fetch_imt_proofs: (a: number, b: number, c: number, d: number, e: any) => any;
export const voting_wasm_init_panic_hook: () => void;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const wasm_bindgen_80140066f03354e2___convert__closures_____invoke___wasm_bindgen_80140066f03354e2___JsValue__core_a76ab548e90a171e___result__Result_____wasm_bindgen_80140066f03354e2___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_80140066f03354e2___convert__closures_____invoke___js_sys_22b816839ce642e1___Function_fn_wasm_bindgen_80140066f03354e2___JsValue_____wasm_bindgen_80140066f03354e2___sys__Undefined___js_sys_22b816839ce642e1___Function_fn_wasm_bindgen_80140066f03354e2___JsValue_____wasm_bindgen_80140066f03354e2___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_80140066f03354e2___convert__closures_____invoke___wasm_bindgen_80140066f03354e2___JsValue______true_: (a: number, b: number, c: any) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
